### ISSUE TITLE
Global `cookieOptions` are not applied in Nuxt 3

### ISSUE THREAD

**Issue by rudolfbyker** [prazdevs/pinia-plugin-persistedstate#291]
### Describe the bug

When using the exact config from the docs https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html#global-options , where stores use localStorage by default, but some stores are explicitly set to use `persist: { storage: persistedState.cookies },`, then the `cookieOptions` seems to be ignored in the stores that use cookies. I still get cookies with `Secure:false` and `SameSite:"None"` for those stores.

### Reproduction

https://stackblitz.com/edit/github-5b43sb

### System Info

```Shell
Stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rudolfbyker** [comment]
Workaround: Specify this everywhere:
```
persistedState.cookiesWithOptions({
  sameSite: "strict",
})
```

**Comment by prazdevs** [comment]
Should be fixed and working in v4

**Comment by rudolfbyker** [comment]
This does not seem to work in v4 either. See https://stackblitz.com/edit/github-5b43sb-n4cbn9?file=nuxt.config.ts

**Comment by prazdevs** [comment]
With v4, you dont need the `@pinia-plugin-persistedstate/nuxt` module, as it is included in the base package. You can refer to this https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt.html#installation

**Comment by rudolfbyker** [comment]
Thanks for the tip. I updated my example, and the global `SameSite` option is still not applied: https://stackblitz.com/edit/github-5b43sb-n4cbn9

**Comment by prazdevs** [comment]
Ok, took me some time to get to it, but I get the issue.

The global cookie options are a way to pass options to stores using cookies as the default.
Passing a storage option to a single store (`storage: `) means passing a "created instance of storage", so you're basically creating a cookieStorage instance.

I made a change to infer global cookieOptions to specified `cookie` storage without parameters (like in your example). It should be available in the next version 🫡

**Comment by hassamxosoft** [comment]
is this issue resolve please can you confirm it i am still getting error?
